[package]
name = "block_game"
version = "0.1.0"
authors = ["Daniel Comisar <daniel.comisar@gmail.com>"]

[dependencies]
ggez = { git = "https://github.com/dc7/ggez.git", rev = "66858fc" }
rand = "0.4"
